create table FEATURES 
(LOCATION VARCHAR(30) primary key, 
 CLASS VARCHAR(30), LATITUDE NUMBER, 
 LONGITUDE NUMBER, MAP VARCHAR(30), 
 ELEV NUMBER);

create table FLOWERS 
(GENUS VARCHAR(30), SPECIES VARCHAR(30), 
 COMNAME VARCHAR(30) primary key );

create table SIGHTINGS 
(NAME VARCHAR(30) , PERSON VARCHAR(30), 
 LOCATION VARCHAR(30) , SIGHTED DATE, 
 CONSTRAINT sightings_pk PRIMARY KEY 
 (NAME, PERSON, LOCATION, SIGHTED));

ALTER TABLE SIGHTINGS
add CONSTRAINT fk1_sightings
  FOREIGN KEY (NAME)
	  REFERENCES FLOWERS(COMNAME);

ALTER TABLE SIGHTINGS
add CONSTRAINT fk2_sightings
  FOREIGN KEY (LOCATION)
	  REFERENCES FEATURES(LOCATION);
