create table PEAK(NAME VARCHAR(30) primary key,ELEV NUMBER,DIFF NUMBER,MAP VARCHAR(30),REGION VARCHAR(30));
create table PARTICIPATED(TRIP_ID NUMBER,NAME VARCHAR(30));
create table CLIMBER(NAME VARCHAR(30),SEX VARCHAR(1));
create table CLIMBED(TRIP_ID NUMBER,PEAK VARCHAR(30),WHEN DATE);